### ISSUE TITLE
different click actions for different rows

### ISSUE THREAD

**Issue by cneud** [cneud/ner.edith#2]
Clicking on a string(token) should trigger different actions based on the different rows:

``LOCATION``: display facsimile snippet  
``POSITION``: ``--undefined--``
``TOKEN``: edit text (for OCR error correction)
``NE-TAG``: drop-down menu of supported NE-Tags  
``NE-EMB``: drop-down menu of supported NE-Tags

**Comment by cneud** [comment]
`POSITION`: `--undefined--` could be used for merges/splits of tokens

**Comment by snmnzl** [comment]
Pre-colored options in drop-down-menu according to supported color of NE-Tag:

NE-TAG: drop-down menu of supported NE-Tags
NE-EMB: drop-down menu of supported NE-Tags

Should simplify and fasten drop-down choice.

**Comment by snmnzl** [comment]
Autocomplete option for drop-down-menu:

`NE-TAG:` drop-down menu of supported NE-Tags
`NE-EMB:` drop-down menu of supported NE-Tags

Should only be triggered by letters "I" or "B", bisects drop-down options and could make scolling in drop-down obsolete.

**Comment by snmnzl** [comment]
Support Strg-Z shortcut for drop-down choices.

**Comment by cneud** [comment]
@snmnzl Thanks for the feedback and suggestions. We will work on the above issue this week and should have a version with the new functionality ready beginning of next week.

Your [last comment](https://github.com/cneud/ner.edith/issues/2#issuecomment-543792803) is for a different issue so I opened a new issue #10 for that.

**Comment by cneud** [comment]
added in 76394e2fc17793494d825c042778c52d18273ec1
