### ISSUE TITLE
display facsimile snippets in the viewer/editor

### ISSUE THREAD

**Issue by cneud** [cneud/ner.edith#4]

**Comment by cneud** [comment]
OCR coordinates via IIIF API

**Comment by snmnzl** [comment]
Will full view of the affiliated TIFF still be possible in addition to the facsimile snippet? Might be important in cases of ambiguous OCR-errors.

**Comment by cneud** [comment]
The desired functionality is to show the immediate token plus its left/right neighbors. Upon clicking them, the full page should open in a separate tab.

**Comment by cneud** [comment]
added in 22e97da8de52cb0dbe1f5969a361183604aa26a0
